server:
  port: 9090

spring:
  application:
    name: karate-mocks-manager
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.karate.mockmgr: DEBUG
    com.intuit.karate: INFO
